language: php
php:
  - '5.6'
  - '7.0'
script: "make migrate_test && make test"
before_install: "composer install --dev"
env:
  global:
  - TWILIO_ACCOUNT_SID=ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  - TWILIO_AUTH_TOKEN=YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
  - TWILIO_NUMBER=+15555555555
  - TWIML_APPLICATION_SID=APZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
